### ISSUE TITLE
`brew upgrade rye` not pulling in 0.37

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/rye#1254]
### Steps to Reproduce

It looks like approximately two hours ago, version 0.37.0 of Rye was just released. On my Mac with macOS Sonoma version 14.5, it seems the [`rye` homebrew formula](https://formulae.brew.sh/formula/rye) lags behind by a minor version:

```none
> brew upgrade rye
Warning: rye 0.36.0 already installed
```

Any chance we can update something in the release process to also update Homebrew? How often is Homebrew updated?

Also, it would be nice to document the `brew` formula in the installation docs: https://rye.astral.sh/guide/installation/

Currently a search for `brew` yields 0 results

### Expected Result

`brew upgrade rye` to pull in the latest version of `rye`

### Actual Result

`brew upgrade rye` didn't pull in 0.37, considers 0.36 the latest version

### Version Info

rye 0.36.0
commit: 0.36.0 (2024-07-07)
platform: macos (aarch64)
self-python: cpython@3.12.3
symlink support: true
uv enabled: true

**Comment by charliermarsh** [comment]
I believe Homebrew runs on its own schedule: https://github.com/Homebrew/homebrew-core/commit/8f03c2cdb916d313512b6d44f956f6bda479afe8. And I don't think it will even _know_ that a new version has been released until we publish it as the latest release (at which point, it's live). In general, I don't think we can wait for redistributors to update, since redistributors generally follow-on from our own releases.

For what it's worth, I think the Hombrew formula was added independently and isn't an "official" part of the project (though it looks totally normal / correct to me and it's open source so I have no concerns about it).
