### ISSUE TITLE
Third-party packages for global tools

### ISSUE THREAD

**Issue by LeieXoyo** [astral-sh/rye#972]
I installed ipython as a global tool, but I don't know how to install other packages for that ipython, I tried installing uv, and installing third party packages via uv pip install --system, but it seems that ipython still doesn't recognize it, how can I do that please.

**Comment by bluss** [comment]
You have this option: rye tools install --extra-requirement which allows you to add extra packages for the tool install. Consider that the tool install is not really made for this use case - there is no rye feature for incrementally updating a tool environment, nor is there a feature to remember those extra requirements when you want to update the tool install. (However your usage of this - could it be generalized and what kind of new features in rye does it want?)


```
rye tools install --help
Installs a package as global tool. This is an alias of `rye tools install`

...

      --extra-requirement <EXTRA_REQUIREMENT>
          Additional dependencies to install that are not declared by the main package
```

----

Ipython is kind of a case in-between a standalone tool and a python install because it wraps the python interpreter. For example ipython itself has (limited) support for working with packages in a different virtual environment than where it's installed. I'm thinking there are many different solutions for ipython.

**Comment by LeieXoyo** [comment]
Thank you for your answer! You're right, it's not appropriate to think of ipython as a tool. I guess a better way to use it would be to create a 'playground' project and install ipython and any other third-party packages I need!
